[18497] CC - Adição do Thrift e XML da FCC e Nova Ficha de Lotação no repositório de integração
laboratoriobridge/esusab-integracao pull request #103
Opened 2023-11-21 21:09 UTC by Ishunter

2023-11-22 13:55 UTC, nathanmolinari requested changes

2023-11-22 13:55 UTC, nathanmolinari commented on xml-exemplo/Cuidado_Compartilhado;esus.xml
> +    <ineDadoSerializado>0000000003</ineDadoSerializado>
deixar o INE o mesmo da lotacaoEvolucao, pra ficar explicito que cnes, ine e ibge aqui do dadoTransporteTransportXml deve ser igual ao da lotacaoEvolucao.

2023-11-22 13:55 UTC, nathanmolinari commented on thrift/layout-ras/gen-csharp/br/gov/saude/esusab/ras/common/CuidadoCompartilhadoThrift.cs
> +namespace br.gov.saude.esusab.ras.common
o thrift do cuidado ficou no namespace common, ele deve ficar no path` thrift/layout-ras/gen-csharp/br/gov/saude/esusab/ras/cuidadocompartilhado/CuidadoCompartilhadoThrift.cs`
isso vale para todos as linguagens geradas

2023-11-22 13:55 UTC, nathanmolinari commented on thrift/layout-ras/gen-nodejs/cuidado_compartilhado_types.js
> +CuidadoCompartilhadoThrift = module.exports.CuidadoCompartilhadoThrift = function(args) {
pq esse aqui n ficou no common como nas outras linguaguens? o de ruby tb

2023-11-22 15:28 UTC, Ishunter commented on thrift/layout-ras/gen-nodejs/cuidado_compartilhado_types.js
> +CuidadoCompartilhadoThrift = module.exports.CuidadoCompartilhadoThrift = function(args) {
boa pergunta

2023-11-22 21:05 UTC, Andrevmatias approved these changes
Só umas dúvidas em relação ao projeto mesmo :blush: 

Deu até uma nostalgia ver as coisas em C# e Pascal escritos com padrões de 15 anos atrás kkkkkkk

2023-11-22 21:05 UTC, Andrevmatias commented on thrift/layout-ras/gen-csharp/br/gov/saude/esusab/ras/common/LotacaoThrift.cs
> +  #if !SILVERLIGHT
Acho que esse gerador tá "meio" desatualizado :sweat_smile: Silverlight era o concorrente do Flash

2023-11-22 21:05 UTC, Andrevmatias commented on thrift/layout-ras/gen-nodejs/cuidado_compartilhado_types.js
> +CuidadoCompartilhadoThrift = module.exports.CuidadoCompartilhadoThrift = function(args) {
mas o que fica no "common_types" é o tipo da Lotacao né? parece certo...

2023-11-22 21:05 UTC, Andrevmatias commented on thrift/layout-ras/thrift/common.thrift
> -
Essas alterações de formatação são propositais?

2023-11-22 21:05 UTC, Andrevmatias commented on XSD/cuidadocompartilhado.xsd
> +      <xs:element maxOccurs="1" name="sexoCidadao" type="xs:long"/>
Existem restrictions de enumeração e valores mínimos e máximos. É padrão não fazer essas validações no schema? Por que as únicas são as de data e nulidade?

2023-11-22 21:05 UTC, Andrevmatias commented on xml-exemplo/Cuidado_Compartilhado.esus.xml
Não precisa alterar a `thrift-exemplo`?

2023-11-23 12:56 UTC, Ishunter commented on thrift/layout-ras/thrift/common.thrift
> -
Eu só copiei do thrift do CN e tirei o que não era pra ir

2023-11-24 12:27 UTC, nathanmolinari commented on XSD/cuidadocompartilhado.xsd
> +      <xs:element maxOccurs="1" name="sexoCidadao" type="xs:long"/>
essas nao ficam no xsd

2023-11-24 12:29 UTC, nathanmolinari commented on thrift/layout-ras/gen-csharp/br/gov/saude/esusab/ras/common/LotacaoThrift.cs
> +  #if !SILVERLIGHT
acho que eh utilizado o gerador da 0.9.3 do thrift, provavelmente se atualizar a versão do thrift deve alterar

2023-11-24 12:32 UTC, nathanmolinari commented on xml-exemplo/Cuidado_Compartilhado.esus.xml
na vdd pelo que olhei dos exemplos parece que são apenas importados os arquivo gerados em java e delphi, acho que vale adicionar os novos la sim

2023-11-28 17:31 UTC, nathanmolinari approved these changes

2023-11-29 13:34 UTC, WillKruscinscki approved these changes

2023-11-29 13:34 UTC, WillKruscinscki commented on xml-exemplo/Cuidado_Compartilhado.esus.xml
> +            <cpf>05339339947</cpf>
```suggestion
            <cpf>94792820030</cpf>
```

2023-12-01 13:06 UTC, merged