Evoluir esusab.integracao de acordo com a evolução na obrigatoriedade da orientação sexual e identidade de gênero
laboratoriobridge/esusab-integracao pull request #110
Opened 2024-02-16 14:49 UTC by nicolaseliasxyz

Close  #19372

2024-02-16 15:35 UTC, feragost requested changes
Tu executou o main e tentou importar o zip no PEC a partir do branch da nova demanda?
Se é pra criar um novo thrift, é interessante que ele funcione pra versão que tu montou.

2024-02-16 15:35 UTC, feragost commented on thrift-exemplo/java/src/main/java/exemplo/ExemploFIchaCadastroIndividualThrift.java
> +public class ExemploFIchaCadastroIndividualThrift {
```suggestion
public class ExemploFichaCadastroIndividualThrift {
```

2024-02-16 15:35 UTC, feragost commented on thrift-exemplo/java/src/main/java/exemplo/ExemploFIchaCadastroIndividualThrift.java
> +		VersaoThrift versaoThrift = new VersaoThrift(3, 2, 3);
Não deveria ser colocado a versão atual da API? 5.4.0?

2024-02-16 15:47 UTC, TiagoGama approved these changes

2024-02-16 15:47 UTC, TiagoGama commented on thrift-exemplo/java/src/main/java/exemplo/ExemploFIchaCadastroIndividualThrift.java
> +public class ExemploFIchaCadastroIndividualThrift {
```suggestion
public class ExemploFichaCadastroIndividualThrift {
```

2024-02-16 15:47 UTC, TiagoGama commented on thrift-exemplo/java/src/main/java/exemplo/ExemploFIchaCadastroIndividualThrift.java
> +public class ExemploFIchaCadastroIndividualThrift {
corrigir nome do arquivo tb

2024-02-16 15:49 UTC, TiagoGama commented on thrift-exemplo/java/src/main/java/exemplo/ExemploFIchaCadastroIndividualThrift.java
> +public class ExemploFIchaCadastroIndividualThrift {
Considerando que isso é um exemplo de como utilizar, acho que os campos deveriam estar mais descritos, com mais comentários.

2024-02-19 17:40 UTC, arthurwinck approved these changes
Vou aprovar e deixar o to fix, essa issue vai pra external review?

2024-02-22 17:35 UTC, merged