20187 - Disponibilizar os thrifts e xmls novos no esusab-integracao
laboratoriobridge/esusab-integracao pull request #120
Opened 2024-05-24 19:48 UTC by alisson-fs

closes laboratoriobridge/pec#20187

2024-05-27 13:14 UTC, wagnerbsantos requested changes
Ajustar o circunferencia abdominal em alguns lugares.
Gerar alguns arquivos dnv com base no branch onde o circunferência abdominal está corrigido.
Remover alguns arquivos do pr que não alterou nada (não marquei todos)

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift-exemplo/java/src/main/java/br/gov/saude/esus/ras/atendindividual/ExameThrift.java
Esse aqui da pra tirar do pr

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift-exemplo/java/src/main/java/br/gov/saude/esus/ras/atendindividual/ProblemaCondicaoAvaliacaoAIThrift.java
tirar do pr

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift-exemplo/java/src/main/java/br/gov/saude/esus/ras/atendodonto/FichaAtendimentoOdontologicoMasterThrift.java
tirar do pr

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift-exemplo/java/src/main/java/br/gov/saude/esus/ras/atendodonto/ProcedimentoQuantidadeThrift.java
tirar do pr

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift-exemplo/java/src/main/java/br/gov/saude/esus/ras/atendprocedimentos/FichaProcedimentoMasterThrift.java
tirar do pr

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift-exemplo/java/src/main/java/br/gov/saude/esus/ras/common/MedicoesThrift.java
Acho que é melhor gerar esse thrift dnv a partir do branch de versionamento.
Aqui ta com `circuferenciaAbdominal` ainda

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/gen-csharp/br/gov/saude/esusab/ras/common/MedicoesThrift.cs
gerar esse aqui dnv tbm

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/gen-javabean/br/gov/saude/esusab/ras/atendindividual/ExameThrift.java
remover do pr

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/gen-javabean/br/gov/saude/esusab/ras/atendindividual/FichaAtendimentoIndividualMasterThrift.java
remover do pr

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/gen-javabean/br/gov/saude/esusab/ras/atendindividual/ProblemaCondicaoAvaliacaoAIThrift.java
remover do pr

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/gen-javabean/br/gov/saude/esusab/ras/common/MedicoesThrift.java
gerar dnv

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/gen-nodejs/common_types.js
gerar dnv

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/gen-php/br/gov/saude/esusab/ras/common/Types.php
gerar dnv

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/gen-py/br/gov/saude/esusab/ras/common/ttypes.py
gerar dnv

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/gen-rb/common_types.rb
gerar dnv

2024-05-27 13:14 UTC, wagnerbsantos commented on thrift/layout-ras/thrift/common.thrift
> +    1:optional double circuferenciaAbdominal;
```suggestion
    1:optional double circunferenciaAbdominal;
```

2024-05-27 13:14 UTC, wagnerbsantos commented on XSD/medicoes.xsd
> +      <xs:element minOccurs="0" name="circuferenciaAbdominal" type="xs:double"/>
```suggestion
      <xs:element minOccurs="0" name="circunferenciaAbdominal" type="xs:double"/>
```

2024-05-27 13:14 UTC, wagnerbsantos commented on xml-exemplo/Atendimento_Individual.esus.xml
> +				<circuferenciaAbdominal>50.0</circuferenciaAbdominal>
```suggestion
				<circunferenciaAbdominal>50.0</circunferenciaAbdominal>
```
Ajustar o circunferencia abdominal nos exemplos

2024-05-27 18:30 UTC, alisson-fs commented
Retirei alguns arquivos do PR e fiz alguns ajustes com base nos comentários do Wag. A geração dos arquivos é feita através de um .sh que existe no repositório esusab-integracao, então não faria diferença regerar após o versionamento.

2024-05-27 23:30 UTC, wesleydecezere approved these changes

2024-05-27 23:30 UTC, wesleydecezere commented on thrift/layout-ras/thrift/ficha_atendimento_odonto.thrift
> +    27:optional common.MedicoesThrift medicoes;
Tá certa a indentação?

2024-05-27 23:30 UTC, wesleydecezere commented on thrift-exemplo/java/src/main/java/br/gov/saude/esus/ras/atendprocedimentos/FichaProcedimentoChildThrift.java
Acho que essa não muda depois da https://github.com/laboratoriobridge/pec/issues/20950 né

2024-05-28 19:24 UTC, wagnerbsantos approved these changes

2024-06-03 12:07 UTC, zDudaHang approved these changes

2024-06-03 12:07 UTC, zDudaHang commented on thrift/layout-ras/thrift/ficha_atendimento_odonto.thrift
> +    27:optional common.MedicoesThrift medicoes;
:point_up:

2024-06-03 15:00 UTC, romulofer approved these changes
💯 Esse deu trabalho kkkkkk

2024-06-03 20:31 UTC, glaucio-martins approved these changes

2024-06-10 12:27 UTC, zDudaHang commented
@wagnerbsantos, acho que vale ver com o @nathanmolinari se ele vai revisar ainda ou deixamos travado no teste

2024-09-12 23:58 UTC, zDudaHang commented on thrift/layout-ras/thrift/ficha_atendimento_individual.thrift
> -	9:optional double alturaAcompanhamentoNutricional;
Acho que faltou arrumar os números no thrift, confirma @nathanmolinari ? Ou mantemos assim porque o CN ainda mapeia com esses números?

2024-09-12 23:58 UTC, zDudaHang commented on thrift/layout-ras/thrift/ficha_atendimento_individual.thrift
> -	27:optional double perimetroCefalico;
Aqui vale o mesmo comentário

2024-09-12 23:58 UTC, zDudaHang commented on thrift/layout-ras/thrift/ficha_atendimento_odonto.thrift
> -	23:optional double alturaAcompanhamentoNutricional;
Aqui vale o mesmo comentário

2024-09-12 23:58 UTC, zDudaHang commented on thrift/layout-ras/thrift/ficha_atendimento_procedimento.thrift
> -	14:optional double alturaAcompanhamentoNutricional;
Aqui vale o mesmo comentário

2024-09-12 23:58 UTC, zDudaHang commented on thrift/layout-ras/thrift/ficha_atendimento_individual.thrift
> -	9:optional double alturaAcompanhamentoNutricional;
Depois de arrumar os número, tem que regerar os `Thrift.java`, tá?

2024-09-12 23:58 UTC, zDudaHang commented on thrift-exemplo/java/src/main/java/br/gov/saude/esus/ras/atendprocedimentos/FichaProcedimentoChildThrift.java
Ela deve ter os campos depreciados sim, o problema da issue é que um atendimento individual estava enviando as medições tanto na FAI quanto na FP, sendo que deveria ser só na FAI
Se for um atendimento de procedimentos com o CBO que só preenche a FP, as medições devem ir na FP daí ;)

2024-09-13 13:26 UTC, GuilhermePrandi commented on thrift/layout-ras/thrift/ficha_atendimento_individual.thrift
> -	9:optional double alturaAcompanhamentoNutricional;
Pelo o que olhei ele mapeia por esses números, tanto que tem alguns campos que pulam números, por campos que já foram depreciados

2024-09-13 13:37 UTC, GuilhermePrandi commented on thrift/layout-ras/thrift/ficha_atendimento_individual.thrift
> -	9:optional double alturaAcompanhamentoNutricional;
Após confirmação com o Nathan, não precisa corrigir a ordenação, esse mapeamento ainda vai valer

2024-11-07 15:03 UTC, merged