Remover os campos de FCI e FCDT que não estão no LEDI do projeto esusab-integracao
laboratoriobridge/esusab-integracao pull request #121
Opened 2024-07-14 21:19 UTC by nicolaseliasx

Close #21441

2024-07-16 23:10 UTC, davibridge commented on thrift/layout-ras/thrift/cadastro_domiciliar.thrift
> -	4:optional common.EnderecoLocalPermanenciaThrift enderecoLocalPermanencia,
Eu não manjo muito disso, mas será que tem um motivo para terem removido um campo e não ter atualizado o id dos campos?

2024-07-16 23:11 UTC, davibridge approved these changes
Meu review foi mais focado em verificar se tu "não removeu algo que não faz sentido" kkk

2024-07-17 13:46 UTC, feragost requested changes

2024-07-17 13:46 UTC, feragost commented on thrift/layout-ras/thrift/cadastro_domiciliar.thrift
> +	3:optional common.EnderecoLocalPermanenciaThrift enderecoLocalPermanencia,
Os ids do thrift devem seguir o mesmo id que foi estabelecido no respectivo thrift do projeto ras.thrift.
enderecoLocalPermanencia no ras.thrift tem o id 4, aqui está com o id 3.

Revisar os ids dos outros campos.

```suggestion
	4:optional common.EnderecoLocalPermanenciaThrift enderecoLocalPermanencia,
```

2024-07-17 13:46 UTC, feragost commented on thrift/layout-ras/gen-javabean/br/gov/saude/esusab/ras/atenddomiciliar/FichaAtendimentoDomiciliarChildThrift.java
> +@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2024-07-14")
É bom não regerar os objetos Thrifts para fichas que tu não trabalhou.
O propósito era trabalhar apenas com cadastro domiciliar e cadastro individual.
Acho que existe alguma forma de gerar somente o que tu quer, nem que seja comentando algo no código do gerador.
Ao menos, só commita as coisas que faz parte do escopo da tua issue.

2024-07-17 13:57 UTC, nicolaseliasx commented on thrift/layout-ras/gen-javabean/br/gov/saude/esusab/ras/atenddomiciliar/FichaAtendimentoDomiciliarChildThrift.java
> +@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2024-07-14")
Da pra eu gerar e commitar apenas os que foram alterados, o script gera tudo

```
LANGS="java:beans php delphi csharp rb go py js:node"

for LANG in $LANGS
do
    for FILE in thrift/*.thrift
    do
        echo "Geração do .thrift $FILE para a linguagem $LANG..."
        docker run -v "$PWD:$(pwd)" thrift:0.9.3 thrift -o $(pwd) --gen $LANG $(pwd)/$FILE
    done

done
```

2024-07-17 14:56 UTC, nicolaseliasx commented on thrift/layout-ras/thrift/cadastro_domiciliar.thrift
> -	4:optional common.EnderecoLocalPermanenciaThrift enderecoLocalPermanencia,
Pelo que entendi, tem que arrumar no ras trhift a posicao tbm, entao teria que mexer dos dois lados

2024-07-17 14:56 UTC, feragost requested changes

2024-07-17 14:56 UTC, feragost commented on thrift/layout-ras/thrift/cadastro_domiciliar.thrift
> +    17:optional double longitude;
Latitude e longitude possuem os ids 17 e 18 no projeto ras.thrift.
Dá uma revisada nos ids desse thrift também.

2024-07-17 16:54 UTC, nicolaseliasx commented on thrift/layout-ras/thrift/cadastro_domiciliar.thrift
> +    17:optional double longitude;
Eu dei, acho que foi treta do meu stash ta sujo quando tava desfazendo

2024-07-17 18:24 UTC, feragost approved these changes

2024-07-18 18:12 UTC, arthurwinck approved these changes

2024-07-26 19:28 UTC, davibridge commented
Testes OK!

- Importei uma ficha usando o `xml-exemplo/Cadastro_Individual.esus.xml` nos branchs atuais de produção e piloto do PEC

2024-07-26 19:28 UTC, merged