atualizando xml de exemplo com doses fracionadas
laboratoriobridge/esusab-integracao pull request #144
Opened 2024-11-28 12:19 UTC by biancabridge

2024-11-28 13:24 UTC, tainadacruz submitted a review, later dismissed
🔝 🚀

2024-11-29 11:37 UTC, SagHuns approved these changes
:top:

2024-11-29 12:24 UTC, vitoriapizzutti approved these changes
🚀 🔝

2024-12-02 23:15 UTC, christianaurichzm submitted a review, later dismissed
Boaa! Deixando request para segurar o pr até a confirmação da versão

2024-12-02 23:15 UTC, christianaurichzm commented on xml-exemplo/Atendimento_Individual.esus.xml
> +				<qtDoseNoite>2</qtDoseNoite>
Só pensei em esses valores de dose serem distintos para quando essa ficha for utilizada como teste não mascare possíveis problemas

2024-12-02 23:15 UTC, christianaurichzm commented on xml-exemplo/Atendimento_Individual.esus.xml
> +	<versao major="6" minor="3" revision="1"/>
Só para não esquecermos de checar a versão antes do merge

2024-12-05 00:07 UTC, PedroBinotto approved these changes
top

2024-12-10 17:01 UTC, nathanmolinari submitted a review, later dismissed

2025-01-21 18:33 UTC, jcaique commented
Esta mesma alteração não será replicada para a Thrift?

2025-02-13 14:47 UTC, PedroBinotto submitted a review, later dismissed

2025-02-14 11:35 UTC, jcaique commented
O arquivo common.thrift não foi alterado. Por aqui utilizamos ele para gerar os fontes.
:(

2025-02-17 13:11 UTC, RicardoJensen requested changes
! :arrow_down: 

Só achei estranho aquilo que perguntei no meu comentário

2025-02-17 13:11 UTC, RicardoJensen commented on thrift-exemplo/delphi/src/thriftesus/br.gov.saude.esusab.ras.common.pas
> +  IProblemaCondicaoThrift = interface;
Porque tem isso e suas atribuições nesse arquivo?

2025-02-17 16:15 UTC, ErFer7 submitted a review, later dismissed
Top :+1:. Não entendi também a alteração no [thrift-exemplo/delphi/src/thriftesus/br.gov.saude.esusab.ras.common.pas](https://github.com/laboratoriobridge/esusab-integracao/pull/144/files#diff-7db22479efed24d5625af4ed0235b2aa98b47888d6410c11badf554ae6464a22).

2025-02-17 19:17 UTC, lucasjoao requested changes

2025-02-17 19:17 UTC, lucasjoao commented on thrift/layout-ras/thrift/common.thrift
> +	16:optional string qtDoseNoite;
Numeração tá errada, vou explicar para vocês na DM o porque.

Vai ter que regerar todos os exemplos novamente.

2025-02-17 19:17 UTC, lucasjoao commented on xml-exemplo/Atendimento_Odontologico.esus.xml
> +	<versao major="6" minor="3" revision="1"/>
Já tava assim, mas me parece pela doc que na verdade saiu na 6.2.0 (https://integracao.esusab.ufsc.br/v620/ledi/documentacao/principais_alteracoes.html).

Deixa como estava e coloca como critério de aceite da issue o QA testar/confirmar isso.

2025-02-17 19:17 UTC, lucasjoao commented on xml-exemplo/Atendimento_Individual.esus.xml
> +			<medicamentos>
Essa especificação tem que ter margem de melhoria, cê precisa seguir algumas definições que eu especifiquei nesse [comentário](https://github.com/laboratoriobridge/pec/issues/23494#issuecomment-2654070117) para que seja o correto aqui.

2025-02-17 19:17 UTC, lucasjoao commented on thrift-exemplo/delphi/src/thriftesus/br.gov.saude.esusab.ras.common.pas
> +  IProblemaCondicaoThrift = interface;
Talvez seja porque quem adicionou não tinha atualizado até então... Mas precisa entender melhor mesmo Binotto.

Além disso, porque não atualizou o exemplo em java daqui? Me parece que faltou coisa.

2025-02-17 20:04 UTC, PedroBinotto commented on thrift-exemplo/delphi/src/thriftesus/br.gov.saude.esusab.ras.common.pas
> +  IProblemaCondicaoThrift = interface;
Como comentei lá na thread, a última pessoa que commitou no arquivo fonte esqueceu de/ optou por não gerar esses arquivos. Por isso o resultado só aparece aqui no meu PR

2025-02-18 22:29 UTC, lucasjoao requested changes
Faltou atualizar a recomendação para QA pedido [aqui](https://github.com/laboratoriobridge/esusab-integracao/pull/144#discussion_r1958694259), não?

Alguns últimos detalhes para ver.

2025-02-18 22:29 UTC, lucasjoao commented on thrift-exemplo/delphi/src/thriftesus/br.gov.saude.esusab.ras.common.pas
> +    field_.ID := 14;
Não faltou atualizar esse arquivo por causa dessa numeração aqui?

2025-02-18 22:29 UTC, lucasjoao commented on xml-exemplo/Atendimento_Odontologico.esus.xml
> +			<medicamentos>
Chegou a importar esse XML? Fiquei em dúvida se realmente deveria ter removido o atributo `dose`...

2025-02-19 19:13 UTC, PedroBinotto commented on xml-exemplo/Atendimento_Odontologico.esus.xml
> +			<medicamentos>
Atualizei o registro de medicamento dos exemplos aqui, copiei direto de uma ficha gerada no PEC ao vivo

2025-02-19 19:22 UTC, PedroBinotto commented on thrift-exemplo/delphi/src/thriftesus/br.gov.saude.esusab.ras.common.pas
Este arquivo estava bem desatualizado. Fiquei meio pasmo com o tamamanho do diff mas, observando que o diff no arquivo fonte apresenta apenas as alterações adequadas, comparei os dois arquivos (`diff thrift/layout-ras/gen-delphi/br.gov.saude.esusab.ras.common.pas thrift-exemplo/delphi/src/thriftesus/br.gov.saude.esusab.ras.common.pas`) e verifiquei que estes estão iguais, mesmo

2025-02-20 14:08 UTC, RicardoJensen submitted a review, later dismissed
! :arrow_down:

2025-02-20 17:15 UTC, lucasjoao commented on xml-exemplo/Atendimento_Odontologico.esus.xml
> +			<medicamentos>
Vou conversar contigo na DM sobre isso.

2025-02-20 17:49 UTC, lucasjoao submitted a review, later dismissed

2025-02-20 18:01 UTC, christianaurichzm approved these changes
:rocket:

2025-02-25 12:23 UTC, lucasjoao commented
> O common.thrift não vai ser atualizado?

Foi atualizado.

2025-02-25 12:23 UTC, lucasjoao commented
> Arquivo xml-exemplo/Atendimento_Individual.esus.xml tag [problemasCondicoes > isAvaliado](https://github.com/laboratoriobridge/esusab-integracao/blob/d86d1a07b30124eecff15d3d4b5d07766ab5bce9/xml-exemplo/Atendimento_Individual.esus.xml#L149): **isAvaliado** é para ser um boolean, de acordo com a [documentação do ESUS](https://integracao.esusab.ufsc.br/ledi/documentacao/estrutura_arquivos/dicionario-fai.html#problemacondicao):
> 
> Acredito que deveria ser true/false, não 1/0, né?

Olá @npeissmann-philips ,

Nós possuimos um canal de suporte para registrar suas demandas relacionadas à Estratégia e-SUS APS, sendo assim, pedimos que insira esta demanda lá: https://esusaps.bridge.ufsc.br/

Ficamos à disposição.

2025-02-27 18:10 UTC, lucasjoao approved these changes

2025-02-27 18:10 UTC, merged