Descontinuando campo de identificacaoUsuario na ficha de consumo alimentar
laboratoriobridge/esusab-integracao pull request #68
Opened 2022-05-30 21:47 UTC by alvarofln

*exemplos recriados com script thrift_build_with_docker.sh (thrift 0.9.3)

2022-05-31 17:23 UTC, lucasjoao requested changes
só verificar ali uma dúvida no xml de exemplo, no resto tá top :rocket: 

ps: não achou estranho as mudanças nos arquivos gerados do .go?

2022-05-31 17:23 UTC, lucasjoao commented on xml-exemplo/Consumo_Alimentar_SeisA23Meses.esus.xml
> -		<identificacaoUsuario>MARTA SILVIANO SILVA</identificacaoUsuario>
testou a importação desses xmls? não precisa alterar a tag `versa` deles lá embaixo?

2022-05-31 17:23 UTC, lucasjoao commented on XSD/fichaconsumoalimentar.xsd
>        <xs:element maxOccurs="1" minOccurs="0" name="cpfCidadao" type="xs:string"/>
isso é mais uma dúvida mesmo, mas já que eles serão obrigatórios, a gente não deveria estar obrigando já aqui no xsd? do jeito que tá aqui com min = 0 ele fica opcional, né?

apesar de que olhando os outros fields parece que o padrão é deixar assim :thinking:

2022-06-02 16:58 UTC, alvarofln commented on XSD/fichaconsumoalimentar.xsd
>        <xs:element maxOccurs="1" minOccurs="0" name="cpfCidadao" type="xs:string"/>
tu nao pode ter os dois preenchidos...é obrigatorio preencher um deles..dai nao pode ser obrigatorio ai

2022-06-02 16:58 UTC, alvarofln commented on xml-exemplo/Consumo_Alimentar_SeisA23Meses.esus.xml
> -		<identificacaoUsuario>MARTA SILVIANO SILVA</identificacaoUsuario>
ahhh boa, a versao tem sim...

2022-06-02 17:24 UTC, lucasjoao commented on XSD/fichaconsumoalimentar.xsd
>        <xs:element maxOccurs="1" minOccurs="0" name="cpfCidadao" type="xs:string"/>
saqueeei, perfeito

2022-07-12 18:12 UTC, merged